### ISSUE TITLE
GV16 (UV index) only mapped on current observations

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/udi-weatherbit-poly#2]
If you got to each forecast day there is a GV16 field but its does not show up in ISY

**Comment by bpaauwe** [comment]
Do you mean that the field doesn't exist on the ISY or that the value of the field is empty on the ISY?

**Comment by macjeff** [comment]
UV Field exists only on the current day (primary node).  Does not exist on the forecast days.  Weatherbit has that info for each day

**Comment by bpaauwe** [comment]
I still don't understand what the issue is.  Here's a screen shot of the weatherbit forecast for tomorrow from the admin console.
![weatherbit-uv](https://user-images.githubusercontent.com/1761223/74955254-3b780d00-53b9-11ea-9611-30a8683b9a3e.png)
It clearly shows the UV index for the day.
If you're not seeing this, then something probably didn't get installed correctly on the ISY.

**Comment by macjeff** [comment]
This is very strange but I had rebooted my admin console a dozen times and I think it was you suggested that I reboot the ISY itself since the CONDITION was showing up in emails as the number and not the text of the condition.  I did not check this after the reboot and its there now.  So very strange but I will close this.
