### ISSUE TITLE
Weather Alerts

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/udi-weatherbit-poly#6]
I wrote about this in your Aeris weather also.  I see weatherbit has an API for alerts.  Would really like it.

https://www.weatherbit.io/api/alerts

**Comment by bpaauwe** [comment]
Please provide an example of how you would like to see that information from the alert displayed using node numeric values?

**Comment by macjeff** [comment]
Can’t UDI add code for it like 

001 is tornado and they translate in ISY?

If not watches and warnings for tornado.  Severe thunderstorm.    Winter weather advisory.   Winter storm warning.   Blizzard warning.    High wind watch warning and advisory. Might be nice to have dense fog and flood warning.

**Comment by bpaauwe** [comment]
But the alerts look like this:
`{  
                 "title":"Winter Weather Advisory issued February 9 at 3:17AM CST expiring February 10 at 12:00PM CST by NWS St Louis MO",
                 "description":"* WHAT...Mixed precipitation expected. Total snow and sleet\naccumulations of less than one inch, and ice accumulations of\nup to one tenth of an inch expected.\n\n* WHERE...Portions of east central and southeast Missouri and\nsouthwest Illinois.\n\n* WHEN...From midnight tonight to noon CST Sunday.\n\n* ADDITIONAL DETAILS...Plan on slippery road conditions.",
                 "severity":"Advisory",
                 "effective_utc":"2019-02-09T09:17:00",
                 "effective_local":"2019-02-09T04:17:00",
                 "expires_local":"2019-02-09T18:00:00",
                 "expires_utc":"2019-02-09T23:00:00",
                 "uri":"https:\/\/api.weather.gov\/alerts\/NWS-IDP-PROD-3362405-2942405",
                 "regions":[  
                    "St. Francois",
                    "Reynolds",
                    "Randolph",
                    "Ste. Genevieve",
                    "Washington",
                    "Crawford",
                    "Madison",
                    "Iron"
                 ]
              },`
How does that translate to a fixed set of numeric values in a node?  What if there is more than one alert?  Do you know the wording for all alerts so that a parser can be written to parse out what the alert is for and translate it to a fixed list of alert types? 

It's pretty easy for you or I to look at that info and pull out what we're interested in, but it's just not structured enough to map to an ISY node.  Also the fact that it's not a fixed number of alerts but some random 0 - ? number that can be present and the ISY nodes are fixed devices. 

I'm not saying it is impossible to do, just very difficult and not something I can tackle in my free time.

**Comment by macjeff** [comment]
Hmm   might be tough. A code would work but might be too much.

Jeff

**Comment by macjeff** [comment]
I will close this as I guess not really possible
